"""v1: exchange domain schema

Revision ID: 7c81f1d77f74
Revises: 
Create Date: 2025-05-18 16:10:01.774555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c81f1d77f74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_exchange_id',
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('exchange_id')
    )
    op.create_table('dim_exchange_info',
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_launched', sa.String(length=25), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('blog_url', sa.String(length=500), nullable=True),
    sa.Column('fee_url', sa.String(length=500), nullable=True),
    sa.Column('fiats', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['dim_exchange_id.exchange_id'], ),
    sa.PrimaryKeyConstraint('exchange_id')
    )
    op.create_table('dim_exchange_map',
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('snapshot_str', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('maker_fee', sa.Float(), nullable=True),
    sa.Column('taker_fee', sa.Float(), nullable=True),
    sa.Column('weekly_visits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['dim_exchange_id.exchange_id'], ),
    sa.PrimaryKeyConstraint('exchange_id', 'snapshot_timestamp')
    )
    op.create_table('fact_exchange_assets',
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('snapshot_str', sa.String(), nullable=False),
    sa.Column('spot_volume_usd', sa.Float(), nullable=True),
    sa.Column('blockchain_symbol', sa.String(length=20), nullable=True),
    sa.Column('blockchain_name', sa.String(length=100), nullable=True),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('crypto_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('currency_price_usd', sa.Float(), nullable=True),
    sa.Column('total_usd_value', sa.Float(), nullable=True),
    sa.Column('wallet_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['dim_exchange_id.exchange_id'], ),
    sa.PrimaryKeyConstraint('exchange_id', 'wallet_address', 'crypto_id', 'snapshot_timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_exchange_assets')
    op.drop_table('dim_exchange_map')
    op.drop_table('dim_exchange_info')
    op.drop_table('dim_exchange_id')
    # ### end Alembic commands ###
