"""v4: add fact_global_market table (global metrics domain)

Revision ID: 7ec1855fabdb
Revises: 243445aead18
Create Date: 2025-05-21 00:12:48.689044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec1855fabdb'
down_revision: Union[str, None] = '243445aead18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_global_market',
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('snapshot_str', sa.String(), nullable=False),
    sa.Column('last_updated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_updated_str', sa.String(), nullable=True),
    sa.Column('btc_dominance', sa.Float(), nullable=True),
    sa.Column('eth_dominance', sa.Float(), nullable=True),
    sa.Column('btc_dominance_yesterday', sa.Float(), nullable=True),
    sa.Column('eth_dominance_yesterday', sa.Float(), nullable=True),
    sa.Column('btc_dominance_24h_change', sa.Float(), nullable=True),
    sa.Column('eth_dominance_24h_change', sa.Float(), nullable=True),
    sa.Column('btc_dominance_delta', sa.Float(), nullable=True),
    sa.Column('eth_dominance_delta', sa.Float(), nullable=True),
    sa.Column('check_btc_dominance_delta', sa.Boolean(), nullable=True),
    sa.Column('check_eth_dominance_delta', sa.Boolean(), nullable=True),
    sa.Column('active_cryptocurrencies', sa.Integer(), nullable=True),
    sa.Column('total_cryptocurrencies', sa.Integer(), nullable=True),
    sa.Column('active_market_pairs', sa.Integer(), nullable=True),
    sa.Column('active_exchanges', sa.Integer(), nullable=True),
    sa.Column('total_exchanges', sa.Integer(), nullable=True),
    sa.Column('defi_market_cap', sa.Float(), nullable=True),
    sa.Column('defi_volume_24h', sa.Float(), nullable=True),
    sa.Column('defi_volume_24h_reported', sa.Float(), nullable=True),
    sa.Column('defi_24h_percentage_change', sa.Float(), nullable=True),
    sa.Column('defi_volume_share', sa.Float(), nullable=True),
    sa.Column('check_defi_volume_share', sa.Boolean(), nullable=True),
    sa.Column('stablecoin_market_cap', sa.Float(), nullable=True),
    sa.Column('stablecoin_volume_24h', sa.Float(), nullable=True),
    sa.Column('stablecoin_volume_24h_reported', sa.Float(), nullable=True),
    sa.Column('stablecoin_24h_percentage_change', sa.Float(), nullable=True),
    sa.Column('stablecoin_market_share', sa.Float(), nullable=True),
    sa.Column('check_stablecoin_market_share', sa.Boolean(), nullable=True),
    sa.Column('derivatives_volume_24h', sa.Float(), nullable=True),
    sa.Column('derivatives_volume_24h_reported', sa.Float(), nullable=True),
    sa.Column('derivatives_24h_percentage_change', sa.Float(), nullable=True),
    sa.Column('altcoin_market_cap', sa.Float(), nullable=True),
    sa.Column('altcoin_volume_24h', sa.Float(), nullable=True),
    sa.Column('altcoin_volume_24h_reported', sa.Float(), nullable=True),
    sa.Column('total_market_cap', sa.Float(), nullable=True),
    sa.Column('total_volume_24h', sa.Float(), nullable=True),
    sa.Column('total_volume_24h_reported', sa.Float(), nullable=True),
    sa.Column('market_liquidity_ratio', sa.Float(), nullable=True),
    sa.Column('check_market_liquidity_ratio', sa.Boolean(), nullable=True),
    sa.Column('total_market_cap_yesterday', sa.Float(), nullable=True),
    sa.Column('total_volume_24h_yesterday', sa.Float(), nullable=True),
    sa.Column('total_market_cap_yesterday_change', sa.Float(), nullable=True),
    sa.Column('total_volume_24h_yesterday_change', sa.Float(), nullable=True),
    sa.Column('total_crypto_dex_currencies', sa.Integer(), nullable=True),
    sa.Column('new_cryptos_today', sa.Integer(), nullable=True),
    sa.Column('new_cryptos_last_24h', sa.Integer(), nullable=True),
    sa.Column('new_cryptos_last_7d', sa.Integer(), nullable=True),
    sa.Column('new_cryptos_last_30d', sa.Integer(), nullable=True),
    sa.Column('new_cryptos_today_pct', sa.Float(), nullable=True),
    sa.Column('crypto_growth_rate_30d', sa.Float(), nullable=True),
    sa.Column('check_crypto_growth_rate_30d', sa.Boolean(), nullable=True),
    sa.Column('max_daily_new_cryptos', sa.Integer(), nullable=True),
    sa.Column('max_new_cryptos_day', sa.Date(), nullable=True),
    sa.Column('min_daily_new_cryptos', sa.Integer(), nullable=True),
    sa.Column('min_new_cryptos_day', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_global_market')
    # ### end Alembic commands ###
