"""v5: add fact_market_sentiment table (fear & greed domain)

Revision ID: c1918ae03efd
Revises: 7ec1855fabdb
Create Date: 2025-05-21 20:18:07.735787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1918ae03efd'
down_revision: Union[str, None] = '7ec1855fabdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_market_sentiment',
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('snapshot_str', sa.String(), nullable=False),
    sa.Column('fear_greed_score', sa.Integer(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_market_sentiment')
    # ### end Alembic commands ###
